### ISSUE TITLE
Time to change Jabber to XMPP?

### ISSUE THREAD

**Issue by Neustradamus** [HaikuArchives/Renga#44]
It is XMPP since 2004, I think it is time to change it ;)
- https://xmpp.org/

**Comment by pulkomandy** [comment]
Help identifying the places that still mention "Jabber" welcome.

**Comment by Neustradamus** [comment]
https://github.com/HaikuArchives/Renga/search?utf8=%E2%9C%93&q=jabber&type=

**Comment by incrypt0** [comment]
FIrst of all how to build it a run ?

**Comment by pulkomandy** [comment]
You need ot install gloox (available in HaikuDepot). Then it goes the usual way for CMake based projects. 

```
mkdir build
cd build
cmake ..
make
```

This will generate the Renga executable in the build directory.

**Comment by korli** [comment]
A "disabled" recipe at HaikuPorts would also be nice (easier to kick off)

**Comment by pulkomandy** [comment]
So, all the things in the "jabber" directory is old code from Jabber4BeOS that I am slowly replacing to use gloox, or moving to network/ and ui/ directories so we can see better the purpose of each file. I don't really want to rename them precisely because it's clear this way that it's legacy code.
