### ISSUE TITLE
Option for having multiple windows

### ISSUE THREAD

**Issue by bitigchi** [HaikuArchives/Renga#75]
With a uni-window where only a single chat window is visible, it is not possible open multiple windows and keep track of multiple flowing conversations. It also limits flexibility using the screen real estate.

Having the contacts displayed in a separate window would allow greater spatial flexibility and use much less screen real estate. It should also allow closing the contacts window and have the chats still be active.

Maybe following options can be considered:

- Hide chat pane (only leaving the contacts list)
- Double click on the contact to open a single chat window

I realise that the trend started by applications like Slack favours single windows, but in reality some people still prefer multiple windows that allows much greater flexibility.

**Comment by pulkomandy** [comment]
I removed the multi window mooe because working with a dozen window is a mess, and it's not coming back.

**Comment by bitigchi** [comment]
What is the harm in leaving the issue open in case someone wants to implement and maintain it?

**Comment by pulkomandy** [comment]
It will create a mess in the code which is not oesigned to handle multiple threads, and in the ui which is not designed for that. Find or write another client designed to work that way.
